language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t zoolake/react-test-app -f ./frontend/Dockerfile.dev ./frontend

sciprt:
  - docker run -e CI=true zoolake/react-test-app npm run test

after_success:
  - docker build -t zoolake/docker-frontend ./frontend
  - docker build -t zoolake/docker-backend ./backend
  - docker build -t zoolake/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push zoolake/docker-frontend
  - docker push zoolake/docker-backend
  - docker push zoolake/docker-nginx
